version: "3"

services:

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass redis
    volumes:
      - "redis:/data"
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    ports:
      - "5432:5432"
    volumes:
      - "db:/var/lib/postgresql/data"

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "5555:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=dev@localhost
      - PGADMIN_DEFAULT_PASSWORD=password
  dj-dividend:
    container_name: dividend
    build: backend
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:80"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    volumes:
      - ./backend:/code
    ports:
      - "80:80"
    depends_on:
      - db
      - redis
      - celery

  celery:
    build: .
    command: celery -A dividends worker --beat --scheduler django_celery_beat.schedulers:DatabaseScheduler -l info
    depends_on:
      - redis
      - db

volumes:
  redis:
  db:
  node_modules:
