version: "3"

services:
  redis:
    image: redis:alpine
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    ports:
      - "5432:5432"
    volumes:
      - "db:/var/lib/postgresql/data"

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "5555:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=dev@localhost
      - PGADMIN_DEFAULT_PASSWORD=password

  dj-dividend:
    container_name: dividend
    build: backend
    command: sh -c "python manage.py wait_for_db && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:80"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    volumes:
      - ./backend:/code
    ports:
      - "80:80"
    depends_on:
      - db
      - redis
  celery:
    build: .
    command: celery -A backend worker -l info
    volumes:
      - ./backend:/code
    depends_on:
      - db
      - redis
  celery-beat:
    build: .
    command: celery -A backend beat -l info
    volumes:
      - ./backend:/code
    depends_on:
      - db
      - redis
volumes:
  db:

