version: "3"

services:
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    ports:
      - "5432:5432"
    volumes:
      - "db:/var/lib/postgresql/data"

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "5555:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=dev@localhost
      - PGADMIN_DEFAULT_PASSWORD=password
  dj-dividend:
    container_name: dividend
    build: backend
    command: bash -c " python manage.py wait_for_db && python manage.py makemigrations && python manage.py migrate && python manage.py crontab add && python manage.py update_stocks && python manage.py update_unsupported_stocks && python manage.py runserver 0.0.0.0:80 &&   python manage.py process_tasks"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    volumes:
      - ./backend:/code
    ports:
      - "80:80"
    depends_on:
      - db


volumes:
  db:
  node_modules:
